- name: Install Java
  yum:
    name: java-1.8.0-openjdk-devel
    update_cache: yes
    state: present
- name: Install Jenkins Repository
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
- name: Import RPM key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
- name: Install daemonize dependency for Jenkins
  command: amazon-linux-extras install epel -y # repository that provides 'daemonize'
- name: Install /etc/yum.repos.d/jenkins.repo
  yum:
    name: jenkins
    update_cache: yes
    state: present
- name: Install Docker
  yum: 
    name: docker
    update_cache: yes
    state: present